config/routes.rb
Rails.application.routes.draw do

resources :tasks
  # lire toutes les tasks
  # get "tasks" => "tasks#index"
  # # lire une task
  # get "tasks/:id" => "tasks#show", as: 'task'
  # # créer une task
  # get "tasks/new" => "tasks#new"
  # post "tasks" => "tasks#create"
  # # updater une task
  # get "tasks/:id/edit" => "tasks#edit"
  # patch "tasks/:id" => "tasks#update"
  # # supprimer une task
  # delete "tasks/:id" => "tasks#destroy"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to task_path(@task)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:content, :date, :rating)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManagerTrails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task do |f|%>
  <%= f.label :content, "enter a content" %>
  <%= f.text_field :content %>

  <%= f.label :content, "date" %>
  <%= f.date_field :date %>

  <%= f.label :content, "rating" %>
  <%= f.number_field :rating %>

  <%= f.submit %>
<% end %>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Edit a task</h1>
<p>be efficient</p>

<%= render 'form' %>

<!-- <form action="/tasks" method="post">
  <input type="text" name="task[content]">
  <input type="text" name="task[date]">
  <input type="number" name="task[rating]">
  <input type="submit" value="Create task">
</form>
 -->

app/views/tasks/index.html.erb
<h1>Voici les tâches</h1>
<p>********************</p>

<%= link_to "Add a new task", new_task_path %>

<% @tasks.each do |task| %>
  <h2><%= task.content %></h2>
  <p><%= task.date %></p>
  <p><%= task.rating %></p>
  <%= link_to "Allez voir", task_path(task) %>
  <%= link_to "Delete a task", task_path(task), method: :delete, data: {confirm: "Are you sure?" } %>

  <p>********************</p>
<% end %>

app/views/tasks/new.html.erb
<h1>Create a new task</h1>
<p>be productive</p>

<%= render 'form' %>

app/views/tasks/show.html.erb
  <h1><%= @task.content %></h1>
  <p><%= @task.date %></p>
  <p><%= @task.rating %></hp>

<%= link_to "retour",tasks_path %>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>